import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';
import { rimraf } from 'rimraf';
import { toJSONSchema } from 'zod/v4';
import {
	componentsJsonSchema,
	registryItemSchema,
	registrySchema,
	type Registry,
	type RegistryItemType
} from '@shadcn-svelte/registry';
import { buildRegistry } from './crawl';
import { loadConfig } from './config';
import { writeFileWithDirs } from './utils';

const OUTPUT_ITEM_TYPES = [
	'registry:ui',
	'registry:hook',
	'registry:component',
	'registry:lib',
	'registry:block',
	'registry:style'
] as const satisfies readonly RegistryItemType[];

const OUTPUT_ITEM_TYPE_SET = new Set<RegistryItemType>(OUTPUT_ITEM_TYPES);

const OUTPUT = {
	registryJson: 'registry.json',
	schemas: 'static/schema',
	internalRegistry: 'src/__registry__'
} as const;

export async function build(): Promise<void> {
	const config = await loadConfig();

	if (config.plugins) {
		for (const plugin of config.plugins) {
			await plugin.buildStart?.();
		}
	}

	const prettierConfig = await prettier.resolveConfig(import.meta.url);
	if (!prettierConfig) throw new Error('Failed to resolve prettier config.');

	const registry = await buildRegistry(config);

	// Validate: no self-references
	const selfReferenced = registry.filter((item) => {
		const localName = `local:${item.name}`;
		return (
			item.registryDependencies.includes(item.name) || item.registryDependencies.includes(localName)
		);
	});
	if (selfReferenced.length) {
		const msg = selfReferenced.map((item) => `  - '${item.name}' depends on itself`).join('\n');
		throw new Error(`Self-referencing registry items:\n${msg}`);
	}

	// Validate: no duplicate names
	const nameCounts = new Map<string, number>();
	for (const item of registry) {
		nameCounts.set(item.name, (nameCounts.get(item.name) ?? 0) + 1);
	}
	const duplicates = [...nameCounts.entries()].filter(([, count]) => count > 1);
	if (duplicates.length) {
		const msg = duplicates
			.map(([name, count]) => `  - '${name}' appears ${count} times`)
			.join('\n');
		throw new Error(`Duplicate registry item names:\n${msg}`);
	}

	const registryInput: Registry = {
		$schema: `./${OUTPUT.schemas}/registry.json`,
		name: config.name,
		homepage: config.homepage,
		aliases: config.aliases,
		...(config.overrideDependencies && {
			overrideDependencies: config.overrideDependencies
		}),
		items: [...registry]
	};

	const result = registrySchema.parse(registryInput, { jitless: true });

	const filteredItems = result.items.filter((item) => OUTPUT_ITEM_TYPE_SET.has(item.type));
	const registryJsonPath = path.resolve(OUTPUT.registryJson);
	const registryJson = JSON.stringify({ ...result, items: filteredItems }, null, '\t');
	const formatted = await prettier.format(registryJson, {
		...prettierConfig,
		filepath: registryJsonPath
	});
	fs.writeFileSync(registryJsonPath, formatted, 'utf8');

	const internalDir = path.resolve(OUTPUT.internalRegistry);
	rimraf.sync(internalDir);

	if (config.dirs?.blocks) {
		const blocks = result.items.filter((item) => item.type === 'registry:block');

		if (blocks.length) {
			const blocksIndex = [
				'// This file is autogenerated by scripts/build-registry/index.ts',
				'// Do not edit this file directly.',
				'export const blocks = [',
				...blocks.map((b) => `"${b.name}",`),
				'] as const;',
				''
			].join('\n');
			writeFileWithDirs(path.resolve(internalDir, 'blocks.ts'), blocksIndex);
		}
	}

	if (config.dirs?.examples) {
		const examples = result.items.filter((item) => item.type === 'registry:example');

		let index =
			'// This file is autogenerated by scripts/build-registry/index.ts\n// Do not edit this file directly.\nexport const Index = {';

		for (const item of examples) {
			const resolveFiles = item.files.map((f) =>
				f.path.replace('src/', '../').replaceAll(path.sep, '/')
			);
			index += `\n"${item.name}": {\n\tfiles: [${resolveFiles.map((f) => `"${f}"`)}],\n},`;
		}

		index += '\n}\n';
		writeFileWithDirs(path.resolve(internalDir, 'index.js'), index);
	}

	const schemaDir = path.resolve(OUTPUT.schemas);

	writeFileWithDirs(
		path.resolve('static', 'schema.json'),
		JSON.stringify(toJSONSchema(componentsJsonSchema), null, '\t')
	);

	writeFileWithDirs(
		path.resolve(schemaDir, 'registry.json'),
		JSON.stringify(toJSONSchema(registrySchema), null, '\t')
	);

	writeFileWithDirs(
		path.resolve(schemaDir, 'registry-item.json'),
		JSON.stringify(toJSONSchema(registryItemSchema), null, '\t')
	);

	console.log('Registry build complete.');
}
